#!/usr/bin/python3

import sys
import os
import re
import argparse
import itertools
import functools
import math
import time
from collections import defaultdict
from copy import deepcopy
from sympy import symbols, solve
from math import floor, ceil
from functools import cmp_to_key

import pygame
from pygame import Color

debug = False

def dbg(s):
    if debug:
        print(s)

# From python 3.12
def batched(iterable, n):
    # batched('ABCDEFG', 3) --> ABC DEF G
    if n < 1:
        raise ValueError('n must be at least one')
    it = iter(iterable)
    while batch := tuple(itertools.islice(it, n)):
        yield batch

offsets = {
    "N": (0, -1),
    "S": (0, 1),
    "E": (1, 0),
    "W": (-1, 0),
}

dirs = {
    "|": "NS",
    "-": "EW",
    "L": "NE",
    "J": "NW",
    "7": "SW",
    "F": "SE",
}

def move(p, d):
    return (p[0] + offsets[d][0], p[1] + offsets[d][1])

def run(args):

    f = open(args.path, "r")
    lines = f.read().splitlines()

    pipes = {}

    for y, l in enumerate(lines):
        for x, c in enumerate(l):
            if c == ".":
                continue
            if c == "S":
                start = (x, y)
            else:
                assert c in dirs.keys(), c
                pipes[(x, y)] = c

    def connected(p):
        if p not in pipes:
            return set()
        return {move(p, d) for d in dirs[pipes[p]]}

    def find_loop(start):
        prev = start
        # start in any direction
        p = connected(start).pop()
        path = [p]
        while p != start:
            next = connected(p) - {prev}
            assert len(next) == 1
            prev = p
            p = next.pop()
            path.append(p)
        return path

    def find_inouts():
        inouts = {}
        for y in range(ROWS):
            outside = True
            last_pipe_from = None
            for x in range(COLS):
                p = pipes.get((x, y), '.')
                if p == '.':
                    inouts[x,y] = 'O' if outside else 'I'
                elif p == '|':
                    assert last_pipe_from is None
                    outside = not outside
                elif p == '-':
                    assert last_pipe_from is not None
                else:
                    d = set(dirs[p])
                    assert 'N' in d or 'S' in d
                    if last_pipe_from is None:
                        assert 'E' in d
                        last_pipe_from = (d & {'N', 'S'}).pop()
                    else:
                        assert 'W' in d
                        exit = (d & {'N', 'S'}).pop()
                        if exit != last_pipe_from:
                            outside = not outside
                        last_pipe_from = None
        return inouts

    # find pipe at start position (it's constrained to have exactly 
    # two pipes connected to it)
    for p in dirs.keys():
        pipes[start] = p
        conn = list(connected(start))
        if start in connected(conn[0]) and start in connected(conn[1]):
            break
    else:
        assert False, "No S tile found"

    ROWS = len(lines)
    COLS = len(lines[0])

    # cell size
    CS = min(20, max(4, 1024 // COLS, 1024 // ROWS))

    def draw_pipes(screen, path=None, inout=None):
        draw = pygame.draw
        for x in range(COLS):
            for y in range(ROWS):
                cx = x*CS + CS//2
                cy = y*CS + CS//2
                draw.rect(surface=screen,
                          color=Color('#d0d0d0'),
                          rect=pygame.Rect(x*CS+1, y*CS+1, CS-1, CS-1))
                if (x, y) == start:
                    draw.circle(surface=screen,
                                center=(cx,cy),
                                color=Color("#008000"),
                                radius=CS//3)
                    continue
                if inout and (x, y) in inout:
                    if inout[(x, y)] == "I":
                        col = Color("#8080ff")
                    else:
                        col = Color('#ff8080')
                    draw.rect(surface=screen,
                              color=col,
                              rect=pygame.Rect(x*CS, y*CS, CS, CS))
                p = pipes.get((x, y), '.')
                if p == '.':
                    pass
                else:
                    p1 = (cx, cy)
                    col = Color("black")
                    if path and (x, y) in path:
                        col = Color("red")
                    for d in dirs[p]:
                        p2 = (cx+offsets[d][0]*CS//2, cy+offsets[d][1]*CS//2)
                        draw.line(surface=screen,
                                  start_pos=p1,
                                  end_pos=p2, 
                                  color=col)

    pygame.init()
    screen = pygame.display.set_mode((CS*COLS+1, CS*ROWS+1))

    running = True
    path = None
    inouts = None
    steps_done = 0
    next_step = None
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            if event.type == pygame.MOUSEBUTTONDOWN:
                next_step = steps_done + 1

        screen.fill(Color("white"))
        draw_pipes(screen, path, inouts)
        pygame.display.flip()

        if next_step == 1:
            path = find_loop(start)
            print(len(path)//2)
            steps_done = 1
            next_step = None
        elif next_step == 2:
            # Remove anything that's not part of the loop
            for xy in list(pipes.keys()):
                if xy not in path:
                    pipes[xy] = "."
            steps_done = 2
            next_step = None
        elif next_step == 3:
            # Mark inouts
            inouts = find_inouts()
            print(len([v for v in inouts.values() if v == 'I']))
            steps_done = 3
            next_step = None
        elif next_step == 4:
            break

def main():
    script_name = os.path.basename(__file__)

    parser = argparse.ArgumentParser()
    parser.add_argument('-d', '--debug', action='store_true',
            help='Enable debug')
    parser.add_argument('path', nargs='?', default=f'input-{script_name}.txt',
            help='Path to the input file')

    args = parser.parse_args()
    global debug
    debug = args.debug
    run(args)

main()
