#!/usr/bin/python3

import sys
import os
import re
import argparse
import itertools
from collections import defaultdict
from copy import deepcopy
from sympy import symbols, solve
from math import floor, ceil
from functools import cmp_to_key

debug = False

def dbg(s):
    if debug:
        print(s)

# From python 3.12
def batched(iterable, n):
    # batched('ABCDEFG', 3) --> ABC DEF G
    if n < 1:
        raise ValueError('n must be at least one')
    it = iter(iterable)
    while batch := tuple(itertools.islice(it, n)):
        yield batch

# For P1 then for P2
orders = [
    ['A', 'K', 'Q', 'J', 'T', '9', '8', '7', '6', '5', '4', '3', '2'],
    ['A', 'K', 'Q', 'T', '9', '8', '7', '6', '5', '4', '3', '2', 'J'],
]

def find_type(cards, part):
    counts = defaultdict(int)
    for c in cards:
        counts[c] += 1
    jc = counts['J']
    counts = sorted(counts.items(), key=lambda x: x[1], reverse=True)
    if part == 1:
        counts = [it[1] for it in counts]
    else:
        counts = [it[1] for it in counts if it[0] != 'J'] + [0]
        counts[0] += jc
    dbg((cards, counts))

    if counts[0] == 5:
        return 0
    if counts[0] == 4:
        return 1
    if counts[0] == 3 and counts[1] == 2:
        return 2
    if counts[0] == 3:
        return 3
    if counts[0] == 2 and counts[1] == 2:
        return 4
    if counts[0] == 2:
        return 5
    return 6

def get_key_lambda(part):
    crank = orders[part-1]
    def cmp(a, b):
        if a[0] != b[0]:
            return a[0] - b[0]
        for i in range(len(a[1])):
            if a[1][i] != b[1][i]:
                return crank.index(a[1][i]) - crank.index(b[1][i])
        return 0
    return cmp_to_key(cmp)

# for r in rank:
#     print(r) 
# exit(0)
def run(args):

    f = open(args.path, "r")
    lines = f.read().splitlines()

    for part in (1, 2):
        all = []
        for l in lines:
            cards, bid = l.split(' ')
            t = find_type(cards, part)
            dbg((cards, bid, t))
            all.append((t, cards, bid))

        sum = 0
        for i, v in enumerate(sorted(all, key=get_key_lambda(part),
                                     reverse=True)):
            dbg((i, v))
            bid = v[2]
            sum += int(bid) * (i+1)

        print(sum)


def main():
    script_name = os.path.basename(__file__)

    parser = argparse.ArgumentParser()
    parser.add_argument('-d', '--debug', action='store_true',
            help='Enable debug')
    parser.add_argument('path', nargs='?', default=f'input-{script_name}.txt',
            help='Path to the input file')

    args = parser.parse_args()
    global debug
    debug = args.debug
    run(args)

main()
