#!/usr/bin/python3

from aoc.tools import *
from itertools import combinations, permutations

def run(args):

    ants = defaultdict(list)

    for y, line in enumerate(read_lines(args)):
        for x, c in enumerate(line):
            if c != '.':
                ants[c].append(complex(x,y))
            W = x+1
        H = y+1

    anodes1 = set()
    anodes2 = set()
    for c, pos in ants.items():
        for p1, p2 in permutations(pos, 2):
            offset = p2 - p1
            p = p2
            while 0 <= p.real < H and 0 <= p.imag < W:
                if p - p2 == offset:
                    anodes1.add(p)
                anodes2.add(p)
                p += offset

    print(len(anodes1))
    print(len(anodes2))

main(run)
