#!/usr/bin/python3

import sys
import os
import re
import argparse
from collections import defaultdict
from copy import deepcopy

debug = False

def dbg(s):
    if debug:
        print(s)

def priority(x):
    x = ord(x)
    if x <= ord('Z'):
        return x - ord('A') + 27
    else:
        return x - ord('a') + 1

def run(args):

    cnt1 = 0
    cnt2 = 0

    f = open(args.path, "r")
    tset = []
    for line in f:
        line = line.strip()
        m = re.match(r'(\d+)-(\d+),(\d+)-(\d+)', line)
        assert m
        r1 = range(int(m.group(1)), int(m.group(2))+1)
        r2 = range(int(m.group(3)), int(m.group(4))+1)

        if set(r1) <= set(r2) or set(r2) <= set(r1):
            cnt1 += 1

        if set(r1) & set(r2):
            cnt2 += 1

    print(cnt1)
    print(cnt2)

def main():
    script_name = os.path.basename(__file__)

    if m := re.match(r'(d\d+)a', script_name):
        script_name = m.group(1)

    parser = argparse.ArgumentParser()
    parser.add_argument('-d', '--debug', action='store_true',
            help='Enable debug')
    parser.add_argument('path', nargs='?', default=f'input-{script_name}.txt',
            help='Path to the input file')

    args = parser.parse_args()
    global debug
    debug = args.debug
    run(args)

main()
