#!/usr/bin/python3.8

import sys
import os
import re
import argparse
import math
import time
import heapq
from collections import defaultdict
from itertools import permutations
from copy import deepcopy
from termcolor import colored

debug = False

def dbg(s):
    if debug:
        print(s)

def hit(vx, vy, xmin, xmax, ymin, ymax):
    x = 0
    y = 0

    topy = 0
    while x <= xmax  and y >= ymin:
        if xmin <= x <= xmax and ymin <= y <= ymax:
            return topy
        x += vx
        y += vy
        if y > topy:
            topy = y
        if vx > 0:
            vx -= 1
        vy -= 1

    return None

def run(args):

    f = open(args.path, "r")
    line = f.readline().strip()
    m = re.match(r'target area: x=(-?\d+)..(-?\d+), y=(-?\d+)..(-?\d+)', line)
    xmin, xmax, ymin, ymax = (int(v) for v in m.groups())

    dbg(f"{xmin=} {xmax=} {ymin=} {ymax=}")

    assert xmax > xmin
    assert ymax > ymin
    assert xmin > 0
    assert ymin < 0 and ymax < 0

    maxvx = xmax
    maxvy = abs(ymin)

    best = 0
    cnt = 0
    for vx in range(0, maxvx + 1):
        for vy in range(-maxvy, maxvy + 1):
            if (y := hit(vx, vy, xmin, xmax, ymin, ymax)) is not None:
                if y > best:
                    best = y
                cnt += 1
                dbg(f"FOUND: {vx=} {vy=} {y=}")

    print(best)
    print(cnt)

def main():
    script_name = os.path.basename(__file__)

    parser = argparse.ArgumentParser()
    parser.add_argument('-d', '--debug', action='store_true',
            help='Enable debug')
    parser.add_argument('path', nargs='?', default=f'input-{script_name}.txt',
            help='Path to the input file')

    args = parser.parse_args()
    global debug
    debug = args.debug
    run(args)

main()
