#!/usr/bin/python3.8

import sys
import os
import re
import argparse
import math
import time
from collections import defaultdict, Counter
from copy import deepcopy

debug = False

def dbg(s):
    if debug:
        print(s)

def rotate(x, y, z, n):
    return (
        (x, y, z),
        (-y, x, z),
        (-x, -y, z),
        (y, -x, z),
        (-z, y, x),
        (-y, -z, x),
        (z, -y, x),
        (y, z, x),
        (-x, y, -z),
        (-y, -x, -z),
        (x, -y, -z),
        (y, x, -z),
        (z, y, -x),
        (-y, z, -x),
        (-z, -y, -x),
        (y, -z, -x),
        (x, -z, y),
        (z, x, y),
        (-x, z, y),
        (-z, -x, y),
        (x, z, -y),
        (-z, x, -y),
        (-x, -z, -y),
        (z, -x, -y),
    )[n]

def match(s1, s2):
    for rot in range(24):
        s2rot = set(rotate(*p, rot) for p in s2)
        c = Counter()
        for p1 in s1:
            for p2 in s2rot:
                offset = tuple(p1[i] - p2[i] for i in range(3))
                c[offset] += 1
        offset, cnt = c.most_common(1)[0]
        if cnt >= 12:
            return rot, offset
    return None


def run(args):

    f = open(args.path, "r")
    scanners = []
    cur_sc = None
    for line in f:
        line = line.strip()
        if m := re.search(r'scanner (\d+)', line):
            cur_sc = set()
            scanners.append(cur_sc)
        elif line == '':
            pass
        else:
            cur_sc.add(tuple(int(n) for n in line.split(',')))

    sea = scanners.pop()
    offs = []
    while scanners:
        dbg(f"{len(scanners)=}")
        for sc in scanners:
            if r := match(sea, sc):
                rot, offset = r
                offs.append(offset)
                dbg(f"Found! {rot=} {offset=}")
                for p in sc:
                    p = rotate(*p, rot)
                    p = tuple(p[i] + offset[i] for i in range(3))
                    sea.add(p)
                scanners = [s for s in scanners if s != sc]
                break

    print(len(sea))

    dists = []
    for s1 in offs:
        for s2 in offs:
            dists.append(sum(abs(s1[i]-s2[i]) for i in range(3)))
    print(max(dists))

def main():
    script_name = os.path.basename(__file__)

    parser = argparse.ArgumentParser()
    parser.add_argument('-d', '--debug', action='store_true',
            help='Enable debug')
    parser.add_argument('path', nargs='?', default=f'input-{script_name}.txt',
            help='Path to the input file')

    args = parser.parse_args()
    global debug
    debug = args.debug
    run(args)

main()
