#!/usr/bin/python3.8

import sys
import os
import re
import argparse
import math
import time
import heapq
from pprint import pprint
from collections import defaultdict
from itertools import permutations
from copy import deepcopy

debug = False

def dbg(s):
    if debug:
        print(s)

def comp_prog(lines):
    code = ''
    for l in lines:
        if l.startswith('inp'):
            assert l == 'inp w'
            code += "w = inp.pop(0)\n"
        else:
            cmd, arg1, arg2 = l.split()
            if cmd == 'add':
                code += f"{arg1} = {arg1} + {arg2}\n"
            elif cmd == 'mul':
                code += f"{arg1} = {arg1} * {arg2}\n"
            elif cmd == 'div':
                code += f"{arg1} = int({arg1} / {arg2})\n"
            elif cmd == 'mod':
                code += f"{arg1} = int({arg1} % {arg2})\n"
            elif cmd == 'eql':
                code += f"{arg1} = int(bool({arg1} == {arg2}))\n"
            else:
                raise Exception(f"cmd: {cmd}")
    dbg(code)
    return compile(code, '<string>', 'exec')

def run(args):

    f = open(args.path, "r")
    prog_parts = []
    part = []
    for line in f:
        line = line.strip()
        if line.startswith('inp'):
            if part:
                prog_parts.append(comp_prog(part))
            part = []
        part.append(line)
    if part:
        prog_parts.append(comp_prog(part))

    # To solve both p1 and p2 at once, we keep min and max for each state.
    # Min is updated only once, max with each digit so min has lowest
    # digits and max highest.
    states = {0: ('', '')}

    for i, pp in enumerate(prog_parts):
        new_states = {}
        for d in range(1, 10):
            for z, (digs_min, digs_max) in states.items():
                regs = {"w": 0, "x": 0, "y": 0, "z": z, "inp": [d]}
                inp = [d]
                exec(pp, regs)
                z = regs['z']
                # Keep old min if exists, always update max
                if z in new_states:
                    new_states[z] = (new_states[z][0], digs_max + str(d))
                else:
                    new_states[z] = (digs_min + str(d), digs_max + str(d))
        states = new_states
        print(i, len(prog_parts), len(states))

    print(states[0][0])
    print(states[0][1])

def main():
    script_name = os.path.basename(__file__)

    parser = argparse.ArgumentParser()
    parser.add_argument('-d', '--debug', action='store_true',
            help='Enable debug')
    parser.add_argument('path', nargs='?', default=f'input-{script_name}.txt',
            help='Path to the input file')

    args = parser.parse_args()
    global debug
    debug = args.debug
    run(args)

main()
