#!/usr/bin/python3.8

import sys
import os
import re
import argparse
from collections import defaultdict
from copy import deepcopy

debug = False

def dbg(s):
    if debug:
        print(s)

def run(args):

    f = open(args.path, "r")
    line = f.readline().rstrip()

    nums = [0]*9
    for n in line.split(','):
        nums[int(n)] += 1

    for i in range(256):
        nums.append(nums.pop(0))
        nums[6] += nums[-1]
        if i + 1 in (80, 256):
            print(sum(nums))

def main():
    script_name = os.path.basename(__file__)

    parser = argparse.ArgumentParser()
    parser.add_argument('-d', '--debug', action='store_true',
            help='Enable debug')
    parser.add_argument('path', nargs='?', default=f'input-{script_name}.txt',
            help='Path to the input file')

    args = parser.parse_args()
    global debug
    debug = args.debug
    run(args)

main()
