#!/bin/bash
DAY=$(date +%-d)
echo "DAY=$DAY"
source .env
curl "https://adventofcode.com/2021/day/$DAY/input" \
  -o "input-d${DAY}.txt" \
  -H 'authority: adventofcode.com' \
  -H 'cache-control: max-age=0' \
  -H "cookie: ${COOKIE}" \
  --compressed
